name: Build Test

on: 
  push:
  pull_request:
    paths-ignore:
      - '**/node_modules/**'
      - '.github/**'
      - '.github/*'
    branches-ignore:
      - renovate*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16
      # yarn cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v3.2.4
        id: yarn-cache 
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-
      # execute commands
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - name: Run tests
        run: |
          yarn test